plugins {
    id 'java'
    id 'io.qameta.allure' version "3.0.2"
}

group = 'org.qateam'
version = '1.0-SNAPSHOT'
description = 'Auto tests for Capital.com'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21

    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

ext {
    junitBomVersion = '6.0.3'
    playwrightVersion = '1.58.0'
    slf4jVersion = '2.0.17'
    allureVersion = '2.25.0'
    aspectjVersion = '1.9.25.1'
    jacksonYamlVersion = '3.1.0'
}

dependencies {
    implementation platform("org.junit:junit-bom:$junitBomVersion")
    implementation 'org.junit.jupiter:junit-jupiter'
    implementation 'org.junit.platform:junit-platform-launcher'

    implementation "com.microsoft.playwright:playwright:$playwrightVersion"

    implementation platform("io.qameta.allure:allure-bom:$allureVersion")
    implementation "io.qameta.allure:allure-junit5"
    implementation "io.qameta.allure:allure-attachments"
    runtimeOnly "org.aspectj:aspectjweaver:$aspectjVersion"

    implementation "org.slf4j:slf4j-api:$slf4jVersion"
    implementation "org.slf4j:slf4j-simple:$slf4jVersion"

    implementation "tools.jackson.dataformat:jackson-dataformat-yaml:$jacksonYamlVersion"
}

allure {
    version = allureVersion

}

tasks.register('fatJar', Jar) {
    archiveFileName = 'capital-tests.jar'
    manifest {
        attributes 'Main-Class': 'org.qateam.capital.TestLauncher'
    }
    from sourceSets.main.output
    from sourceSets.test.output
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    exclude 'META-INF/*.SF', 'META-INF/*.DSA', 'META-INF/*.RSA'
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
        exceptionFormat = "full"
    }
    maxParallelForks = Runtime.runtime.availableProcessors()
}

tasks.register('runTests', JavaExec) {
    mainClass = 'org.qateam.capital.TestLauncher'
    classpath = sourceSets.test.runtimeClasspath

}